version: "3"
services:
  web-server:
    container_name: "go-practice-web-server"
    build: 
      context: .
    volumes:
      - .:/go/src/Go_Practice
    working_dir: /go/src/Go_Practice
    command: air -c .air.toml
    ports:
      - 8088:8088
    networks:
      - web_service

networks:
  web_service:
    external: true