// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Go_Practice/app/handler"
)

// Injectors from wire.go:

func InitializeEvent() handler.Event {
	message := handler.NewMessage()
	greeter := handler.NewGreeter(message)
	event := handler.NewEvent(greeter)
	return event
}
