// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BInter is an autogenerated mock type for the BInter type
type BInter struct {
	mock.Mock
}

// Add provides a mock function with given fields: a, b
func (_m *BInter) Add(a int8, b int8) int8 {
	ret := _m.Called(a, b)

	var r0 int8
	if rf, ok := ret.Get(0).(func(int8, int8) int8); ok {
		r0 = rf(a, b)
	} else {
		r0 = ret.Get(0).(int8)
	}

	return r0
}

// Api provides a mock function with given fields: a, b
func (_m *BInter) Api(a int8, b int8) int {
	ret := _m.Called(a, b)

	var r0 int
	if rf, ok := ret.Get(0).(func(int8, int8) int); ok {
		r0 = rf(a, b)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
