// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go_practice/grpc-server/app/Internal/grpc_conn"
)

// Injectors from wire.go:

func Initialize() (grpcconn.IGrpcConn, error) {
	iGrpcConn := grpcconn.ProviderGrpcService()
	return iGrpcConn, nil
}
