// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go_practice/grpc-server/app/Internal/grpc_conn"
	"go_practice/grpc-server/app/handler"
)

// Injectors from wire.go:

func Initialize() (grpcconn.GrpcConn, error) {
	iHealth := handler.ProviderHealthCli()
	iCalculator := handler.ProviderCalculatorCli()
	grpcConn := grpcconn.GrpcConn{
		Health:     iHealth,
		Calculator: iCalculator,
	}
	return grpcConn, nil
}
