// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IBusiness is an autogenerated mock type for the IBusiness type
type IBusiness struct {
	mock.Mock
}

// Add provides a mock function with given fields: a, b
func (_m *IBusiness) Add(a int64, b int64) int64 {
	ret := _m.Called(a, b)

	var r0 int64
	if rf, ok := ret.Get(0).(func(int64, int64) int64); ok {
		r0 = rf(a, b)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Api provides a mock function with given fields: a, b
func (_m *IBusiness) Api(a int, b int) int {
	ret := _m.Called(a, b)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(a, b)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
