// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "Go_Practice/app/model"

	mock "github.com/stretchr/testify/mock"

	structs "Go_Practice/app/global/structs"
)

// IDB is an autogenerated mock type for the IDB type
type IDB struct {
	mock.Mock
}

// DeleteUserInfo provides a mock function with given fields: id
func (_m *IDB) DeleteUserInfo(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserInfo provides a mock function with given fields:
func (_m *IDB) GetUserInfo() ([]model.User, error) {
	ret := _m.Called()

	var r0 []model.User
	if rf, ok := ret.Get(0).(func() []model.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetUserInfo provides a mock function with given fields: req
func (_m *IDB) SetUserInfo(req structs.RawData) error {
	ret := _m.Called(req)

	var r0 error
	if rf, ok := ret.Get(0).(func(structs.RawData) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserInfo provides a mock function with given fields: reqMap
func (_m *IDB) UpdateUserInfo(reqMap map[string]interface{}) error {
	ret := _m.Called(reqMap)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = rf(reqMap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
