// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	structs "Go_Practice/app/global/structs"
)

// IDB is an autogenerated mock type for the IDB type
type IDB struct {
	mock.Mock
}

// SetUserInfo provides a mock function with given fields: req
func (_m *IDB) SetUserInfo(req structs.RawData) error {
	ret := _m.Called(req)

	var r0 error
	if rf, ok := ret.Get(0).(func(structs.RawData) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
