// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRedis is an autogenerated mock type for the IRedis type
type IRedis struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *IRedis) Get(key string) (string, error) {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, value, expiretime
func (_m *IRedis) Set(key string, value interface{}, expiretime int) error {
	ret := _m.Called(key, value, expiretime)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, int) error); ok {
		r0 = rf(key, value, expiretime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
